# Copyright 2024-2025 Christian Mazakas
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

[package]
name = "fiona"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30.1", features = ["event", "socket", "net"] }
slotmap = { version = "1.0.7" }
axboe-liburing = { git = "https://github.com/cmazakas/liburing.git", rev = "73f4ee759a7b1ea5e582f37c68f85772154aec83" }

[dev-dependencies]
futures = "0.3.31"
rand = "0.9.2"
tokio = { version = "1.47.1", features = ["full"] }
clap = { version = "4.5.45", features = ["derive"] }

[profile.release-with-debug]
inherits = "release"
debug = "full"

[profile.lto]
inherits = "release"
lto = "thin"

[[bench]]
name = "echo"
harness = false

[[bench]]
name = "timer"
harness = false

[[bench]]
name = "echo2"
harness = false

[[bench]]
name = "ring_msg"
harness = false
