# Copyright 2024 Christian Mazakas
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

[package]
name = "fiona"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.29.0", features = ["event", "socket", "net"] }
axboe-liburing = { git = "https://github.com/cmazakas/liburing.git", rev = "4d60fbfea2ab3ecd6b1d58de778e2964ff0b2bb7" }

[dev-dependencies]
futures = "0.3.30"
rand = "0.8.5"
tokio = { version = "1.43.0", features = ["full"] }

[profile.release-with-debug]
inherits = "release"
debug = "full"

[[bench]]
name = "echo"
harness = false

[[bench]]
name = "timer"
harness = false
