# Copyright 2024 Christian Mazakas
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

[package]
name = "fiona"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.29.0", features = ["event", "socket", "net"] }
axboe-liburing = { git = "https://github.com/cmazakas/liburing.git", rev = "b549ea565699d55df61596943760aaecc030c8b5" }

[dev-dependencies]
futures = "0.3.30"
rand = "0.8.5"

[profile.release-with-debug]
inherits = "release"
debug = "full"
