# Copyright 2024-2025 Christian Mazakas
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

[package]
name = "fiona"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.29.0", features = ["event", "socket", "net"] }
axboe-liburing = { git = "https://github.com/cmazakas/liburing.git", rev = "20effc01537c2515709ae9e493dd9392e0a6fac3" }

[dev-dependencies]
futures = "0.3.30"
rand = "0.9.0"
tokio = { version = "1.43.0", features = ["full"] }
clap = { version = "4.5.32", features = ["derive"] }

[profile.release-with-debug]
inherits = "release"
debug = "full"

[[bench]]
name = "echo"
harness = false

[[bench]]
name = "timer"
harness = false

[[bench]]
name = "echo2"
harness = false
